# Generated by Django 4.0.3 on 2022-03-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_rename_articlepost_project_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_info',
            name='Project_id',
            field=models.CharField(default='n000', max_length=100),
        ),
    ]
