# Generated by Django 4.0.3 on 2022-03-25 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('center', '0003_project_info_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_info',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project_infos', to=settings.AUTH_USER_MODEL),
        ),
    ]
